// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: property.proto

#include "property.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr VariableMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        read_only_{false},
        value_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR VariableMessage::VariableMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct VariableMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VariableMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VariableMessageDefaultTypeInternal() {}
  union {
    VariableMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VariableMessageDefaultTypeInternal _VariableMessage_default_instance_;

inline constexpr TriggerMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TriggerMessage::TriggerMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TriggerMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TriggerMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TriggerMessageDefaultTypeInternal() {}
  union {
    TriggerMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TriggerMessageDefaultTypeInternal _TriggerMessage_default_instance_;

inline constexpr ResponseMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        variables_{},
        triggers_{},
        error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        variable_{nullptr},
        command_id_{::uint64_t{0u}},
        success_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseMessage::ResponseMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ResponseMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseMessageDefaultTypeInternal() {}
  union {
    ResponseMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseMessageDefaultTypeInternal _ResponseMessage_default_instance_;

inline constexpr CommandMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        variable_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        variable_{nullptr},
        trigger_{nullptr},
        command_id_{::uint64_t{0u}},
        command_type_{static_cast< ::CommandMessage_CommandType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CommandMessage::CommandMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CommandMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandMessageDefaultTypeInternal() {}
  union {
    CommandMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandMessageDefaultTypeInternal _CommandMessage_default_instance_;
static ::_pb::Metadata file_level_metadata_property_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_property_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_property_2eproto = nullptr;
const ::uint32_t TableStruct_property_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::TriggerMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::TriggerMessage, _impl_.name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::VariableMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::VariableMessage, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::VariableMessage, _impl_.name_),
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::VariableMessage, _impl_.read_only_),
    PROTOBUF_FIELD_OFFSET(::VariableMessage, _impl_.value_),
    PROTOBUF_FIELD_OFFSET(::CommandMessage, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CommandMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CommandMessage, _impl_.command_id_),
    PROTOBUF_FIELD_OFFSET(::CommandMessage, _impl_.command_type_),
    PROTOBUF_FIELD_OFFSET(::CommandMessage, _impl_.variable_name_),
    PROTOBUF_FIELD_OFFSET(::CommandMessage, _impl_.variable_),
    PROTOBUF_FIELD_OFFSET(::CommandMessage, _impl_.trigger_),
    ~0u,
    ~0u,
    0,
    1,
    2,
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _impl_.command_id_),
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _impl_.error_message_),
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _impl_.message_),
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _impl_.variable_),
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _impl_.variables_),
    PROTOBUF_FIELD_OFFSET(::ResponseMessage, _impl_.triggers_),
    ~0u,
    ~0u,
    0,
    1,
    2,
    ~0u,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::TriggerMessage)},
        {9, -1, -1, sizeof(::VariableMessage)},
        {23, 36, -1, sizeof(::CommandMessage)},
        {41, 56, -1, sizeof(::ResponseMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_TriggerMessage_default_instance_._instance,
    &::_VariableMessage_default_instance_._instance,
    &::_CommandMessage_default_instance_._instance,
    &::_ResponseMessage_default_instance_._instance,
};
const char descriptor_table_protodef_property_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016property.proto\"\036\n\016TriggerMessage\022\014\n\004na"
    "me\030\001 \001(\t\"\202\001\n\017VariableMessage\022\014\n\004name\030\001 \001"
    "(\t\022\026\n\014string_value\030\003 \001(\tH\000\022\027\n\rnumeric_va"
    "lue\030\004 \001(\001H\000\022\024\n\nbool_value\030\005 \001(\010H\000\022\021\n\trea"
    "d_only\030\006 \001(\010B\007\n\005value\"\343\002\n\016CommandMessage"
    "\022\022\n\ncommand_id\030\001 \001(\004\0221\n\014command_type\030\002 \001"
    "(\0162\033.CommandMessage.CommandType\022\032\n\rvaria"
    "ble_name\030\003 \001(\tH\000\210\001\001\022\'\n\010variable\030\004 \001(\0132\020."
    "VariableMessageH\001\210\001\001\022%\n\007trigger\030\005 \001(\0132\017."
    "TriggerMessageH\002\210\001\001\"s\n\013CommandType\022\020\n\014GE"
    "T_VARIABLE\020\000\022\020\n\014SET_VARIABLE\020\001\022\025\n\021GET_AL"
    "L_VARIABLES\020\002\022\024\n\020GET_ALL_TRIGGERS\020\003\022\023\n\017E"
    "XECUTE_TRIGGER\020\004B\020\n\016_variable_nameB\013\n\t_v"
    "ariableB\n\n\010_trigger\"\204\002\n\017ResponseMessage\022"
    "\022\n\ncommand_id\030\001 \001(\004\022\017\n\007success\030\002 \001(\010\022\032\n\r"
    "error_message\030\003 \001(\tH\000\210\001\001\022\024\n\007message\030\004 \001("
    "\tH\001\210\001\001\022\'\n\010variable\030\005 \001(\0132\020.VariableMessa"
    "geH\002\210\001\001\022#\n\tvariables\030\006 \003(\0132\020.VariableMes"
    "sage\022!\n\010triggers\030\007 \003(\0132\017.TriggerMessageB"
    "\020\n\016_error_messageB\n\n\010_messageB\013\n\t_variab"
    "leb\006proto3"
};
static ::absl::once_flag descriptor_table_property_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_property_2eproto = {
    false,
    false,
    810,
    descriptor_table_protodef_property_2eproto,
    "property.proto",
    &descriptor_table_property_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_property_2eproto::offsets,
    file_level_metadata_property_2eproto,
    file_level_enum_descriptors_property_2eproto,
    file_level_service_descriptors_property_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_property_2eproto_getter() {
  return &descriptor_table_property_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_property_2eproto(&descriptor_table_property_2eproto);
const ::google::protobuf::EnumDescriptor* CommandMessage_CommandType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_property_2eproto);
  return file_level_enum_descriptors_property_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CommandMessage_CommandType_internal_data_[] = {
    327680u, 0u, };
bool CommandMessage_CommandType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr CommandMessage_CommandType CommandMessage::GET_VARIABLE;
constexpr CommandMessage_CommandType CommandMessage::SET_VARIABLE;
constexpr CommandMessage_CommandType CommandMessage::GET_ALL_VARIABLES;
constexpr CommandMessage_CommandType CommandMessage::GET_ALL_TRIGGERS;
constexpr CommandMessage_CommandType CommandMessage::EXECUTE_TRIGGER;
constexpr CommandMessage_CommandType CommandMessage::CommandType_MIN;
constexpr CommandMessage_CommandType CommandMessage::CommandType_MAX;
constexpr int CommandMessage::CommandType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class TriggerMessage::_Internal {
 public:
};

TriggerMessage::TriggerMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TriggerMessage)
}
inline PROTOBUF_NDEBUG_INLINE TriggerMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

TriggerMessage::TriggerMessage(
    ::google::protobuf::Arena* arena,
    const TriggerMessage& from)
    : ::google::protobuf::Message(arena) {
  TriggerMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:TriggerMessage)
}
inline PROTOBUF_NDEBUG_INLINE TriggerMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void TriggerMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TriggerMessage::~TriggerMessage() {
  // @@protoc_insertion_point(destructor:TriggerMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TriggerMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void TriggerMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:TriggerMessage)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* TriggerMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 27, 2> TriggerMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_TriggerMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TriggerMessage, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(TriggerMessage, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\4\0\0\0\0\0\0"
    "TriggerMessage"
    "name"
  }},
};

::uint8_t* TriggerMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TriggerMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TriggerMessage.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TriggerMessage)
  return target;
}

::size_t TriggerMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TriggerMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData TriggerMessage::_class_data_ = {
    TriggerMessage::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* TriggerMessage::GetClassData() const {
  return &_class_data_;
}

void TriggerMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<TriggerMessage*>(&to_msg);
  auto& from = static_cast<const TriggerMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TriggerMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TriggerMessage::CopyFrom(const TriggerMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TriggerMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool TriggerMessage::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* TriggerMessage::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void TriggerMessage::InternalSwap(TriggerMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata TriggerMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_property_2eproto_getter, &descriptor_table_property_2eproto_once,
      file_level_metadata_property_2eproto[0]);
}
// ===================================================================

class VariableMessage::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::VariableMessage, _impl_._oneof_case_);
};

VariableMessage::VariableMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:VariableMessage)
}
inline PROTOBUF_NDEBUG_INLINE VariableMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        value_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

VariableMessage::VariableMessage(
    ::google::protobuf::Arena* arena,
    const VariableMessage& from)
    : ::google::protobuf::Message(arena) {
  VariableMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.read_only_ = from._impl_.read_only_;
  switch (value_case()) {
    case VALUE_NOT_SET:
      break;
      case kStringValue:
        new (&_impl_.value_.string_value_) decltype(_impl_.value_.string_value_){arena, from._impl_.value_.string_value_};
        break;
      case kNumericValue:
        _impl_.value_.numeric_value_ = from._impl_.value_.numeric_value_;
        break;
      case kBoolValue:
        _impl_.value_.bool_value_ = from._impl_.value_.bool_value_;
        break;
  }

  // @@protoc_insertion_point(copy_constructor:VariableMessage)
}
inline PROTOBUF_NDEBUG_INLINE VariableMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        value_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void VariableMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.read_only_ = {};
}
VariableMessage::~VariableMessage() {
  // @@protoc_insertion_point(destructor:VariableMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void VariableMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  if (has_value()) {
    clear_value();
  }
  _impl_.~Impl_();
}

void VariableMessage::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:VariableMessage)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (value_case()) {
    case kStringValue: {
      _impl_.value_.string_value_.Destroy();
      break;
    }
    case kNumericValue: {
      // No need to clear
      break;
    }
    case kBoolValue: {
      // No need to clear
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}


PROTOBUF_NOINLINE void VariableMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:VariableMessage)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.read_only_ = false;
  clear_value();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* VariableMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 5, 0, 40, 2> VariableMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967234,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_VariableMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool read_only = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(VariableMessage, _impl_.read_only_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(VariableMessage, _impl_.read_only_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(VariableMessage, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(VariableMessage, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string string_value = 3;
    {PROTOBUF_FIELD_OFFSET(VariableMessage, _impl_.value_.string_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double numeric_value = 4;
    {PROTOBUF_FIELD_OFFSET(VariableMessage, _impl_.value_.numeric_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // bool bool_value = 5;
    {PROTOBUF_FIELD_OFFSET(VariableMessage, _impl_.value_.bool_value_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kBool)},
    // bool read_only = 6;
    {PROTOBUF_FIELD_OFFSET(VariableMessage, _impl_.read_only_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\17\4\14\0\0\0\0\0"
    "VariableMessage"
    "name"
    "string_value"
  }},
};

::uint8_t* VariableMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:VariableMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "VariableMessage.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  switch (value_case()) {
    case kStringValue: {
      const std::string& _s = this->_internal_string_value();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "VariableMessage.string_value");
      target = stream->WriteStringMaybeAliased(3, _s, target);
      break;
    }
    case kNumericValue: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          4, this->_internal_numeric_value(), target);
      break;
    }
    case kBoolValue: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          5, this->_internal_bool_value(), target);
      break;
    }
    default:
      break;
  }
  // bool read_only = 6;
  if (this->_internal_read_only() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        6, this->_internal_read_only(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VariableMessage)
  return target;
}

::size_t VariableMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:VariableMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // bool read_only = 6;
  if (this->_internal_read_only() != 0) {
    total_size += 2;
  }

  switch (value_case()) {
    // string string_value = 3;
    case kStringValue: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_string_value());
      break;
    }
    // double numeric_value = 4;
    case kNumericValue: {
      total_size += 9;
      break;
    }
    // bool bool_value = 5;
    case kBoolValue: {
      total_size += 2;
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData VariableMessage::_class_data_ = {
    VariableMessage::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* VariableMessage::GetClassData() const {
  return &_class_data_;
}

void VariableMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<VariableMessage*>(&to_msg);
  auto& from = static_cast<const VariableMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:VariableMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_read_only() != 0) {
    _this->_internal_set_read_only(from._internal_read_only());
  }
  switch (from.value_case()) {
    case kStringValue: {
      _this->_internal_set_string_value(from._internal_string_value());
      break;
    }
    case kNumericValue: {
      _this->_internal_set_numeric_value(from._internal_numeric_value());
      break;
    }
    case kBoolValue: {
      _this->_internal_set_bool_value(from._internal_bool_value());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VariableMessage::CopyFrom(const VariableMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VariableMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool VariableMessage::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* VariableMessage::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void VariableMessage::InternalSwap(VariableMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
        swap(_impl_.read_only_, other->_impl_.read_only_);
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata VariableMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_property_2eproto_getter, &descriptor_table_property_2eproto_once,
      file_level_metadata_property_2eproto[1]);
}
// ===================================================================

class CommandMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<CommandMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_._has_bits_);
  static void set_has_variable_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::VariableMessage& variable(const CommandMessage* msg);
  static void set_has_variable(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::TriggerMessage& trigger(const CommandMessage* msg);
  static void set_has_trigger(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::VariableMessage& CommandMessage::_Internal::variable(const CommandMessage* msg) {
  return *msg->_impl_.variable_;
}
const ::TriggerMessage& CommandMessage::_Internal::trigger(const CommandMessage* msg) {
  return *msg->_impl_.trigger_;
}
CommandMessage::CommandMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CommandMessage)
}
inline PROTOBUF_NDEBUG_INLINE CommandMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        variable_name_(arena, from.variable_name_) {}

CommandMessage::CommandMessage(
    ::google::protobuf::Arena* arena,
    const CommandMessage& from)
    : ::google::protobuf::Message(arena) {
  CommandMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.variable_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::VariableMessage>(arena, *from._impl_.variable_)
                : nullptr;
  _impl_.trigger_ = (cached_has_bits & 0x00000004u)
                ? CreateMaybeMessage<::TriggerMessage>(arena, *from._impl_.trigger_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, command_id_),
           offsetof(Impl_, command_type_) -
               offsetof(Impl_, command_id_) +
               sizeof(Impl_::command_type_));

  // @@protoc_insertion_point(copy_constructor:CommandMessage)
}
inline PROTOBUF_NDEBUG_INLINE CommandMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        variable_name_(arena) {}

inline void CommandMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, variable_),
           0,
           offsetof(Impl_, command_type_) -
               offsetof(Impl_, variable_) +
               sizeof(Impl_::command_type_));
}
CommandMessage::~CommandMessage() {
  // @@protoc_insertion_point(destructor:CommandMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CommandMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.variable_name_.Destroy();
  delete _impl_.variable_;
  delete _impl_.trigger_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CommandMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:CommandMessage)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.variable_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.variable_ != nullptr);
      _impl_.variable_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.trigger_ != nullptr);
      _impl_.trigger_->Clear();
    }
  }
  ::memset(&_impl_.command_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.command_type_) -
      reinterpret_cast<char*>(&_impl_.command_id_)) + sizeof(_impl_.command_type_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CommandMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 36, 2> CommandMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CommandMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CommandMessage, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.command_id_)}},
    // .CommandMessage.CommandType command_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CommandMessage, _impl_.command_type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.command_type_)}},
    // optional string variable_name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.variable_name_)}},
    // optional .VariableMessage variable = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.variable_)}},
    // optional .TriggerMessage trigger = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 2, 1, PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.trigger_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 command_id = 1;
    {PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.command_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // .CommandMessage.CommandType command_type = 2;
    {PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.command_type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // optional string variable_name = 3;
    {PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.variable_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .VariableMessage variable = 4;
    {PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.variable_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .TriggerMessage trigger = 5;
    {PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.trigger_), _Internal::kHasBitsOffset + 2, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::VariableMessage>()},
    {::_pbi::TcParser::GetTable<::TriggerMessage>()},
  }}, {{
    "\16\0\0\15\0\0\0\0"
    "CommandMessage"
    "variable_name"
  }},
};

::uint8_t* CommandMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommandMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_command_id(), target);
  }

  // .CommandMessage.CommandType command_type = 2;
  if (this->_internal_command_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_command_type(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional string variable_name = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_variable_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CommandMessage.variable_name");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional .VariableMessage variable = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::variable(this),
        _Internal::variable(this).GetCachedSize(), target, stream);
  }

  // optional .TriggerMessage trigger = 5;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, _Internal::trigger(this),
        _Internal::trigger(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommandMessage)
  return target;
}

::size_t CommandMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CommandMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string variable_name = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_variable_name());
    }

    // optional .VariableMessage variable = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.variable_);
    }

    // optional .TriggerMessage trigger = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.trigger_);
    }

  }
  // uint64 command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_command_id());
  }

  // .CommandMessage.CommandType command_type = 2;
  if (this->_internal_command_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_command_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CommandMessage::_class_data_ = {
    CommandMessage::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CommandMessage::GetClassData() const {
  return &_class_data_;
}

void CommandMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CommandMessage*>(&to_msg);
  auto& from = static_cast<const CommandMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CommandMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_variable_name(from._internal_variable_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_variable()->::VariableMessage::MergeFrom(
          from._internal_variable());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_trigger()->::TriggerMessage::MergeFrom(
          from._internal_trigger());
    }
  }
  if (from._internal_command_id() != 0) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  if (from._internal_command_type() != 0) {
    _this->_internal_set_command_type(from._internal_command_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CommandMessage::CopyFrom(const CommandMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CommandMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CommandMessage::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CommandMessage::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CommandMessage::InternalSwap(CommandMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.variable_name_, &other->_impl_.variable_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.command_type_)
      + sizeof(CommandMessage::_impl_.command_type_)
      - PROTOBUF_FIELD_OFFSET(CommandMessage, _impl_.variable_)>(
          reinterpret_cast<char*>(&_impl_.variable_),
          reinterpret_cast<char*>(&other->_impl_.variable_));
}

::google::protobuf::Metadata CommandMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_property_2eproto_getter, &descriptor_table_property_2eproto_once,
      file_level_metadata_property_2eproto[2]);
}
// ===================================================================

class ResponseMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<ResponseMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_._has_bits_);
  static void set_has_error_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_message(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::VariableMessage& variable(const ResponseMessage* msg);
  static void set_has_variable(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::VariableMessage& ResponseMessage::_Internal::variable(const ResponseMessage* msg) {
  return *msg->_impl_.variable_;
}
ResponseMessage::ResponseMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ResponseMessage)
}
inline PROTOBUF_NDEBUG_INLINE ResponseMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        variables_{visibility, arena, from.variables_},
        triggers_{visibility, arena, from.triggers_},
        error_message_(arena, from.error_message_),
        message_(arena, from.message_) {}

ResponseMessage::ResponseMessage(
    ::google::protobuf::Arena* arena,
    const ResponseMessage& from)
    : ::google::protobuf::Message(arena) {
  ResponseMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.variable_ = (cached_has_bits & 0x00000004u)
                ? CreateMaybeMessage<::VariableMessage>(arena, *from._impl_.variable_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, command_id_),
           offsetof(Impl_, success_) -
               offsetof(Impl_, command_id_) +
               sizeof(Impl_::success_));

  // @@protoc_insertion_point(copy_constructor:ResponseMessage)
}
inline PROTOBUF_NDEBUG_INLINE ResponseMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        variables_{visibility, arena},
        triggers_{visibility, arena},
        error_message_(arena),
        message_(arena) {}

inline void ResponseMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, variable_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, variable_) +
               sizeof(Impl_::success_));
}
ResponseMessage::~ResponseMessage() {
  // @@protoc_insertion_point(destructor:ResponseMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ResponseMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.error_message_.Destroy();
  _impl_.message_.Destroy();
  delete _impl_.variable_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ResponseMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:ResponseMessage)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.variables_.Clear();
  _impl_.triggers_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.error_message_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.message_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.variable_ != nullptr);
      _impl_.variable_->Clear();
    }
  }
  ::memset(&_impl_.command_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.command_id_)) + sizeof(_impl_.success_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ResponseMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 3, 44, 2> ResponseMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ResponseMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 command_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ResponseMessage, _impl_.command_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.command_id_)}},
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ResponseMessage, _impl_.success_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.success_)}},
    // optional string error_message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.error_message_)}},
    // optional string message = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.message_)}},
    // optional .VariableMessage variable = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 2, 0, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.variable_)}},
    // repeated .VariableMessage variables = 6;
    {::_pbi::TcParser::FastMtR1,
     {50, 63, 1, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.variables_)}},
    // repeated .TriggerMessage triggers = 7;
    {::_pbi::TcParser::FastMtR1,
     {58, 63, 2, PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.triggers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 command_id = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.command_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.success_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // optional string error_message = 3;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.error_message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string message = 4;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.message_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .VariableMessage variable = 5;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.variable_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .VariableMessage variables = 6;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.variables_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .TriggerMessage triggers = 7;
    {PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.triggers_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::VariableMessage>()},
    {::_pbi::TcParser::GetTable<::VariableMessage>()},
    {::_pbi::TcParser::GetTable<::TriggerMessage>()},
  }}, {{
    "\17\0\0\15\7\0\0\0"
    "ResponseMessage"
    "error_message"
    "message"
  }},
};

::uint8_t* ResponseMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ResponseMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_command_id(), target);
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_success(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional string error_message = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_error_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ResponseMessage.error_message");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string message = 4;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ResponseMessage.message");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional .VariableMessage variable = 5;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, _Internal::variable(this),
        _Internal::variable(this).GetCachedSize(), target, stream);
  }

  // repeated .VariableMessage variables = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_variables_size()); i < n; i++) {
    const auto& repfield = this->_internal_variables().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .TriggerMessage triggers = 7;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_triggers_size()); i < n; i++) {
    const auto& repfield = this->_internal_triggers().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(7, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResponseMessage)
  return target;
}

::size_t ResponseMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResponseMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .VariableMessage variables = 6;
  total_size += 1UL * this->_internal_variables_size();
  for (const auto& msg : this->_internal_variables()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .TriggerMessage triggers = 7;
  total_size += 1UL * this->_internal_triggers_size();
  for (const auto& msg : this->_internal_triggers()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string error_message = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_error_message());
    }

    // optional string message = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_message());
    }

    // optional .VariableMessage variable = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.variable_);
    }

  }
  // uint64 command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_command_id());
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ResponseMessage::_class_data_ = {
    ResponseMessage::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ResponseMessage::GetClassData() const {
  return &_class_data_;
}

void ResponseMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ResponseMessage*>(&to_msg);
  auto& from = static_cast<const ResponseMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ResponseMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_variables()->MergeFrom(
      from._internal_variables());
  _this->_internal_mutable_triggers()->MergeFrom(
      from._internal_triggers());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_error_message(from._internal_error_message());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_message(from._internal_message());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_variable()->::VariableMessage::MergeFrom(
          from._internal_variable());
    }
  }
  if (from._internal_command_id() != 0) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResponseMessage::CopyFrom(const ResponseMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResponseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ResponseMessage::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ResponseMessage::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ResponseMessage::InternalSwap(ResponseMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.variables_.InternalSwap(&other->_impl_.variables_);
  _impl_.triggers_.InternalSwap(&other->_impl_.triggers_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.success_)
      + sizeof(ResponseMessage::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(ResponseMessage, _impl_.variable_)>(
          reinterpret_cast<char*>(&_impl_.variable_),
          reinterpret_cast<char*>(&other->_impl_.variable_));
}

::google::protobuf::Metadata ResponseMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_property_2eproto_getter, &descriptor_table_property_2eproto_once,
      file_level_metadata_property_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
